server:
  port: 8921

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: HOSPITAL-SERVICE
          uri: lb://HOSPITAL-SERVICE
          predicates:
            - Path=/hospital/**

        - id: PATIENT-SERVICE
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/users/**

        - id: PHARMACY-SERVICE
          uri: lb://PHARMACY-SERVICE
          predicates:
            - Path=/pharmacy/**

        - id: FEEDBACK-SERVICE
          uri: lb://FEEDBACK-SERVICE
          predicates:
            - Path=/ratings/**

        - id: AUTHENTICATION-SERVICE
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/v1/auth/**


# Okta configurations for api gateway
okta:
  oauth2:
    issuer: https://dev-50075498.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaacs7sh9J30s9aD5d7
    client-secret: pbwlwyimThN1RhKckHSRfvTKIjws-8sAIfq_MJRS
    scopes: openid, profile, email, address, phone, offline_access
