server:
  port: 8083

spring:
  devtools:
    add-properties: 'true'
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pharmacy?zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  application:
    name: Pharmacy-Service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka