server:
  port: 8083

spring:
  devtools:
    add-properties: 'true'
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pharmacy?zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  application:
    name: Pharmacy-Service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Resilience4j Properties
resilience4j:
  circuitbreaker:
    instances:
      ratingMedicineBreakerAll:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

      ratingMedicineBreakerLikeName:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

      ratingMedicineBreakerByComposition:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED