server:
  port: 8181

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hospital?zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  devtools:
    add-properties: true
  application:
    name: Hospital-Service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 160000000
#        readTimeout: 160000000

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

# Resilience4j Properties
resilience4j:
  #  Circuit Breaker
  circuitbreaker:
    circuit-breaker-aspect-order: 2
    instances:
      ratingDoctorBreakerAll:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

      ratingDoctorBreakerById:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

      ratingDoctorBreakerByEmail:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

      ratingDoctorBreakerByEitherName:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  # Retry
  retry:
    retry-aspect-order: 3 # Higher Order higher priority
    instances:
      ratingDoctorRetryAll:
        max-attempts: 3
        wait-duration: 2s
#       *** reference -> https://refactorfirst.com/spring-cloud-resiliance4j-circuitbreaker-and-retry
#        enable-exponential-backoff: true
#        exponential-backoff-multiplier: 2
#        retry-exceptions:
#          - org.springframework.web.client.RestClientException
#        ignore-exceptions:
#          - io.management.hospital.IgnoreException

      ratingDoctorRetryById:
        max-attempts: 3
        wait-duration: 2s

      ratingDoctorRetryByEmail:
        max-attempts: 3
        wait-duration: 2s

      ratingDoctorRetryByEitherName:
        max-attempts: 3
        wait-duration: 2s

  ratelimiter:
    rate-limiter-aspect-order: 1
    instances:
      ratingDoctorLimit:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 0s