server:
    port: 8082

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/hospital?zeroDateTimeBehavior=convertToNull
        username: root
        password: root
    devtools:
        add-properties: true
    application:
      name: Hospital-Service
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka