server:
  port: 8081

# log files
logging:
  file:
    name: C:/Temp/Logs/HMS/patient.log

spring:
  devtools:
    add-properties: 'true'
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/patient?zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  application:
    name: Patient-Service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    jdbc:
      repositories:
        enabled: false  # Due to Multiple JPA Repositories
  config:
    import: optional:configserver:http://localhost:8902