server:
  port: 8081

# JWT Mapping keys
jwt:
  secret: your_jwt_secret
  expiration: 1800000

# log files
logging:
  file:
    name: C:/Temp/Logs/HMS/patient.log

spring:
  devtools:
    add-properties: 'true'
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/patient?zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  application:
    name: Patient-Service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true