server:
    port: 8381

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/ratings?zeroDateTimeBehavior=convertToNull
        username: root
        password: root
    devtools:
        add-properties: true
    application:
        name: Feedback-Service
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true