server:
  port: 8381

# log files
logging:
  file:
    name: C:/Temp/Logs/HMS/feedback.log

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ratings?zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  devtools:
    add-properties: true
  application:
    name: FEEDBACK-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8902