server:
  port: 8902

spring:
  application:
    name: CONFIG-SERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ishubhn/hospital-management-external-config
          clone-on-start: true
          basedir: /temp/HMS-config

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka